import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full" style={{ background: '#e0e1e3' }}>
        <div style={{
          maxWidth: '480px',
          margin: '0 auto',
          minHeight: '100dvh',
          position: 'relative',
          background: '#f4f5f7',
          boxShadow: '0 0 40px rgba(0, 0, 0, 0.12)'
        }}>
          {children}
        </div>
      </body>
    </html>
  );
}
